"""add search_radius_km to executors

Revision ID: 16123769769e
Revises: e09b9980ab5e
Create Date: 2026-04-08 21:00:00.905843

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '16123769769e'
down_revision: Union[str, None] = 'e09b9980ab5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executors', sa.Column('search_radius_km', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executors', 'search_radius_km')
    # ### end Alembic commands ###
