"""add city to campaigns

Revision ID: e09b9980ab5e
Revises: 39c7a5fd67d4
Create Date: 2026-04-08 15:56:37.596566

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e09b9980ab5e'
down_revision: Union[str, None] = '39c7a5fd67d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('city', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'city')
    # ### end Alembic commands ###
